"""add str telegram id field

Revision ID: 13f1e59fd4a1
Revises: db690c951ea4
Create Date: 2026-01-16 19:09:55.273584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f1e59fd4a1'
down_revision: Union[str, Sequence[str], None] = 'db690c951ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('telegram_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'telegram_id')
    # ### end Alembic commands ###
